### ISSUE TITLE
Option to disable connect/disconnect notifications

### ISSUE THREAD

**Issue by Stebalien** [fregante/GhostText#109]
This information is usually conveyed by both the browser action icon and the blue halo around the active text field. Personally, I find the the notifications to be a bit intrusive and annoying.

**Comment by bfred-it** [comment]
That’s a good idea. For now you can use Stylish or Adblock to target and hide the element because I don’t know when I’ll have time to add the options.

**Comment by Stebalien** [comment]
Fair enough.

**Comment by eugenesvk** [comment]
I've blocked the the element with uBlock Origin, thanks for the tip, but the bigger issue remains - the fact that notification appears at all also makes the browser become the front app when I close the tab in the editor, for example, which is unwanted

**Comment by eugenesvk** [comment]
I've added this option if you'd like to help testing it by manually loading the extension from this folder

https://github.com/eugenesvk/GhostText/tree/tmp/distribution
