### ISSUE TITLE
Safari WebExtension support

### ISSUE THREAD

**Issue by gibfahn** [fregante/GhostText#171]
See similar issues in Refined GitHub and Vimium: https://github.com/sindresorhus/refined-github/issues/14 https://github.com/philc/vimium/issues/3610

Now Safari is growing Webextensions support it would be great if GhostText could work there too, it's one of my "can't live without" extensions that keeps me on Chrome...

**Comment by fregante** [comment]
This would be great, but I don't think it will happen since it requires a yearly $99 subscription. I'd be happy to publish it there once that changes.

**Comment by fregante** [comment]
I published it now! Let me know if you have any issues with it

https://apps.apple.com/app/ghosttext/id1552641506

**Comment by gibfahn** [comment]
Just tried it, looks like it's working perfectly, thanks!
