### ISSUE TITLE
Support for Google Colab

### ISSUE THREAD

**Issue by calpa** [fregante/GhostText#190]
# Setup

Browser: Google Chrome
Editor: VSCode

# Description
Can I use GhostText with Google Colab?

**Comment by indigoviolet** [comment]
@fregante Is there any form of documentation indicating how one might debug/add support for a site on which GhostText doesn't work? I'm interested in getting it to work on Colab.

**Comment by fregante** [comment]
"Support" is made of 2 parts:

- detection (which in this case it _could_ be URL-based, but ideally attribute-based)
- read/write value

If the value an be set via DOM, like for a standard contentEditable, the second point would be easy:

https://github.com/fregante/GhostText/blob/a3ac72db5c05edbe0d4e2cef70c1a4fd5cdfd11b/source/ghost-text.js#L12-L29

In the more likely case where you have to access the website’s own script data, you'd have to go through the `AdvancedTextWrapper`, which communicates with the `unsafe-messenger` script to get and set the text:

https://github.com/fregante/GhostText/blob/a3ac72db5c05edbe0d4e2cef70c1a4fd5cdfd11b/source/unsafe-messenger.js#L33-L52

You can see the above piece of code uses a local `CodeMirror` property and then sends the value via events.

**Comment by fregante** [comment]
It looks like Google Colab uses Monaco editor, which is tracked here:

- https://github.com/fregante/GhostText/issues/140

I'd definitely love to add support for it.

**Comment by fregante** [comment]
Support was added in v23.3.11 🎉 

https://github.com/fregante/GhostText/releases/tag/23.3.11
