### ISSUE TITLE
Firefox installation failed with `Download failed. Please check your connection.` error

### ISSUE THREAD

**Issue by Matts966** [fregante/GhostText#200]
# Setup

Browser: Firefox 85.0.2 (64 bit)

# Description

[Ghost Text](https://addons.mozilla.org/en-US/firefox/addon/ghosttext/) installation on firefox is failing, though other plugins are installed normally.

![スクリーンショット 2021-02-21 23 27 39](https://user-images.githubusercontent.com/28551465/108628128-6699ae80-749c-11eb-8966-627cd902fab8.png)

**Comment by fregante** [comment]
Thanks for the report. I'll contact Mozilla

**Comment by fregante** [comment]
I thin you should be able to install an older version in the meanwhile: https://addons.mozilla.org/en-US/firefox/addon/ghosttext/versions/

**Comment by fregante** [comment]
It has already been fixed!
