### ISSUE TITLE
Multiple fields don’t work correctly at once

### ISSUE THREAD

**Issue by fregante** [fregante/GhostText#201]
I just noticed a screencast in this article where having 2 fields select meant you could override both with a single editor tab. That’s now how it should work. 😰 

https://applech2.com/archives/20210216-ghosttext-for-safari.html

**Comment by subnut** [comment]
This **must** be specific to the sublime text plugin. My plugin doesn't behave like that. It opens each field in new tab. See GIF -

![gifcast_210223204157](https://user-images.githubusercontent.com/56714626/108864158-d7021600-75e9-11eb-84b2-72c97e7dc1fe.gif)

**Comment by fregante** [comment]
It’s a little strange because each field as its own websocket if I remember correctly, so this feels like messages would be mixed in the browser

**Comment by subnut** [comment]
> It’s a little strange because each field as its own websocket if I remember correctly, so this feels like messages would be mixed in the browser

Umm.. I actually couldn't understand what you tried to say... :sweat_smile:

**Comment by subnut** [comment]
@fregante Can you reproduce this issue using the Sublime text plugin? I just checked and the issue doesn't seem to occur at all. It behaves as intended!

**Comment by fregante** [comment]
It seems that the video in the article uses Atom, which is similar to the VS Code plugin as well. I haven’t had time to replicate

**Comment by fregante** [comment]
ST seems to work correctly, but VS Code is super buggy in every way:

- the connection doesn't close when closing the editor’s tab, you have to close the whole window
- closing the tab will lose the textarea content altogether
- enabling 2 fields will work for a moment, but then it will stop as you switch back and forth

**Comment by fregante** [comment]
So it appears that it's an issue with Atom and VS Code. Closing this issue here
