### ISSUE TITLE
Chrome Web Store removal notice

### ISSUE THREAD

**Issue by fregante** [fregante/GhostText#208]
> Hi there,
> 
> We wanted to let you know that your item is at risk of being removed from the Chrome Web Store. Please find the details below.
> 
> 
> Item name: GhostText
> 
> Item ID: godiecgffnchndlihlpaajjcplehddca
> 
> Violation(s):
> 
> Code Readability Requirements
> 
> Violation reference ID: Red Titanium
> Violation: Having obfuscated code in the package.
> Violating content:
> Code snippet: background.js:0:0: var $2b3195ddb06fb912df5be5730a7eba5c$var$proto = "undefined" != typeof Element ? Element.prototype : {}; var $2b3195ddb06fb912df5be5730a7eba5c$var$vendor = $2b3195ddb06fb912df5be5730a7eba5c$var$proto.matches || $2b3195ddb06fb912df5be5730a7eba5c$var$proto.matchesSelector || $2b3195ddb06fb912df5be5730a7eba5c$var$proto.webkitMatchesSelector || $2b3195ddb06fb912df5be5730a7eba5c$var$proto.mozMatchesSelector || $2b3195ddb06fb912df5be5730a7eba5c$var$proto.msMatchesSelector || $2b3195ddb06fb912df5be5730a7eba5c$var$proto.oMatchesSelector;
> Code snippet: options.js:0:0: var $2b3195ddb06fb912df5be5730a7eba5c$var$proto = "undefined" != typeof Element ? Element.prototype : {}; var $2b3195ddb06fb912df5be5730a7eba5c$var$vendor = $2b3195ddb06fb912df5be5730a7eba5c$var$proto.matches || $2b3195ddb06fb912df5be5730a7eba5c$var$proto
> Code snippet: ghost-text.js:0:0: var $5856072928a22ee416029f7f78d4d652$exports = {}; var $5856072928a22ee416029f7f78d4d652$var$define;
> How to rectify: Replace the obfuscated code with human-readable code and resubmit the item.
> Relevant section of the program policy:
> Developers must not obfuscate code or conceal functionality of their extension. (learn more)
> 
> 
> Important information about resubmission:
> 
> Please make the necessary changes within 14 days in order to avoid removal.
> 
> Once you have made these changes you may submit and publish a new draft in the Chrome Web Store Developer Dashboard.
> 
> Your draft will then be reviewed for policy compliance. If the outcome of the review is successful, your existing store listing will get replaced by the approved draft. However, if the new draft fails to comply with our policies, both the draft and the existing store listing will be removed.
> 
> 
> Do you believe this was a mistake?
> 
> You can use this Support Page to learn more about this violation and get in touch with us.
> 
> 
> We value developer contributions to the Chrome Web Store, and look forward to helping you bring your item into compliance with our policies.
> 
> Thanks,
> 
> Chrome Web Store Developer Support
>

**Comment by fregante** [comment]
40 minutes later:

> Hi there,
> 
> We regret to inform you that your item has been removed from the Chrome Web Store. Please find the details below.
> 
> 
> Item name: GhostText
> 
> Item ID: godiecgffnchndlihlpaajjcplehddca
> 
> Violation(s):
> 
> 
> We have not received an update from you on your Google Chrome item before the expiration of the warning period specified in our earlier email.
> 
> Because your item continues to not comply with our policies stated in the previous email, it has now been removed from the Chrome Web Store.

**Comment by fregante** [comment]
This has already been addressed and hopefully it will be reinstated soon. I pushed an updated that should look less "obfuscated" (it never was).

Related: https://github.com/parcel-bundler/parcel/issues/6092

**Comment by darkred** [comment]
The extension is again in CWS !

**Comment by fregante** [comment]
Thank god. And thanks for the update! They approved the latest version which includes #205 as well
