### ISSUE TITLE
Sublime Text 4 support?

### ISSUE THREAD

**Issue by jtran** [fregante/GhostText#210]
# Setup

Browser: Firefox latest (88.0.1)
Editor: Sublime Text

# Description

Does it work with Sublime Text 4?  I recently upgraded from 3, where GhostText was working perfectly, and I now get the error message "Unable to connect to the editor."  I wonder, is it a problem on my end, or does GhostText simply not support Sublime Text 4?  I see no mention of which versions of Sublime are supported, and the Sublime package hasn't been updated in years.

**Comment by fregante** [comment]
Thank you for the issue! I opened a PR for package control. Thankfully it seems to work out of the box, it's just that it's currently marked as ST3-only in the package repository.

For the record, it resides on https://github.com/GhostText/GhostText-for-SublimeText

**Comment by jtran** [comment]
I saw that the PR was closed.  So I tried removing the package from Sublime and re-installing it, and it works.  I'm typing this using GhostText now.  So I'm not sure what went wrong in the upgrade.  I guess I should have tried this initially.  I think this issue can be closed, but I'll leave it up to you.

Anyway, thanks so much for the quick reply, and also for making GhostText!

**Comment by fregante** [comment]
Indeed 🤷‍♂️ 

I don’t know why it didn’t appear at first, I didn’t have it installed at all.
