### ISSUE TITLE
Unknown function: yarp#py3

### ISSUE THREAD

**Issue by yefeiyu** [fregante/GhostText#211]
# Setup

Browser: osx
Editor: vim

# Description
Error detected while processing /Users/****/.vim/plugged/vim-ghost/plugin/vim_compat.vim:                                     
line    5:
E117: Unknown function: yarp#py3

**Comment by fregante** [comment]
Sorry, that's probably related to vim or the vim plugin you're using. There's no `yarp` anywhere in the browser side. Try opening an issue in the vim ghost text repository.

**Comment by emezeta** [comment]
when opening anything in vim, it just says:

> Error detected while processing /home/my_home/.vim/plugged/vim-ghost/plugin/vim_compat.vim:
> line    5:
> E117: Unknown function: yarp#py3
> E15: Invalid expression: yarp#py3('ghost_wrapper')
> 

before starting in its usual command mode

**Comment by tecfu** [comment]
The error message is because vim-ghost depends on the following nvim plugin: https://github.com/SpaceVim/nvim-yarp

To fix the issue using vim-plug:

```
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'SpaceVim/nvim-yarp'
Plug 'raghur/vim-ghost'
```


See also: https://github.com/raghur/vim-ghost/issues/42
