### ISSUE TITLE
Please add support as Microsoft Edge browser extension 

### ISSUE THREAD

**Issue by snowman** [fregante/GhostText#217]

**Comment by fregante** [comment]
It already supports it, you can install it from the chrome store

**Comment by snowman** [comment]
wow, I didn't know about that, thank you ❤️ 

#### steps to install `GhostText` from `Microsoft Edge`:
1. Open  page `edge://extensions/`
2. On the Bottom Left, turn `Allow extensions from other stores` switch ON, then select `Allow` in confirm dialog
3. Install [GhostText](https://chrome.google.com/webstore/detail/ghosttext/godiecgffnchndlihlpaajjcplehddca)
