### ISSUE TITLE
Keyboard shortcuts conflicts with GitHub command palette

### ISSUE THREAD

**Issue by MrChocolatine** [fregante/GhostText#218]
Hello @fregante.

Currently the keyboard shortcut to connect to GhostText is:

https://github.com/fregante/GhostText/blob/765dc7a6834c6a7b47eeb67daf14c0ac3cff3ea6/source/manifest.json#L47-L48

But it conflicts with GitHub's keyboard shortcut for its command palette:

https://github.blog/changelog/2021-10-27-command-palette-beta/

I am on Mac, using your extension, and I cannot invoke the command palette in "command mode". (unless I disable GhostText)

I would understand if you don't want to change it immediately, since the command palette is still in beta.

Thanks.

**Comment by fregante** [comment]
The shortcuts can be customized: https://ghosttext.fregante.com/#keyboard-shortcuts

Every shortcut has a conflict somewhere 😅

**Comment by fregante** [comment]
Plus I see no conflict, the shortcut is not the same. In this video you can see:

1. cmd+k brings up the palette
2. cmd+shift+k activates GT
3. cmd+r to reload
4. cmd+shift+k activates GT (no conflict with GitHub)

https://user-images.githubusercontent.com/1402241/139715459-02b86745-2840-4a20-9dea-b111962e9a54.mov

**Comment by MrChocolatine** [comment]
> The shortcuts can be customized: https://ghosttext.fregante.com/#keyboard-shortcuts

Dang... And I know the page `chrome://extensions/shortcuts` actually, I just barely never use it. Thanks for the reminder and sorry for the useless issue.

> Plus I see no conflict, the shortcut is not the same. In this video you can see:

There is a conflict yes.

The command palette can be opened in 2 modes, `cmd + K` and `cmd + shift + K`.

_The extension GhostText was disabled when recording_

https://user-images.githubusercontent.com/47531779/139716856-cc81cb17-cdde-45d0-8417-ab8edcbf89ef.mov

**Comment by fregante** [comment]
Yes indeed that's why I _resolved_ my comment 😉

**Comment by MrChocolatine** [comment]
A custom shortcut via `chrome://extensions/shortcuts` did the trick, obviously :v: .

> Yes indeed that's why I resolved my comment 😉

I thought it was GitHub Refined that automatically collapsed the comment é_è .

**Comment by jtran** [comment]
I understand that GhostText cannot avoid collisions with everything, but GitHub isn't a tiny site in the long tail.  I started using GhostText specifically so that I could write long GitHub comments using my editor of choice.  I suspect that a large number of GhostText users are also GitHub users, and they're going to run into this.

Basically, I'm only asking, can you reconsider this issue?

**Comment by fregante** [comment]
@jtran what's the issue? What browser are you using?

**Comment by jtran** [comment]
I already customized the keyboard shortcut in Firefox before finding this GitHub issue.  The problem is that I don't think GhostText users should need to do this.  GhostText no longer works out of the box, and that's a poor user experience.

**Comment by fregante** [comment]
There is nothing I can do about this, every shortcut is used somewhere. I can't make it optional, it's just how extensions work. The complaint should be made toward Chrome. Even if I change it here I'll break something else even on GitHub itself in the future.
