### ISSUE TITLE
The text  in the contenteditable text box don't came back in with the real line-breaks

### ISSUE THREAD

**Issue by ousigieg** [fregante/GhostText#224]
# Setup

Browser:  Chrome 101.0.4951.41
Editor: Emacs  28.1

# Description

If the content in the contenteditable text box is as follows in https://ghosttext.fregante.com/test.
(1) This is a contenteditable div
(2) abc
(3) 123
![image](https://user-images.githubusercontent.com/19954880/165986235-2c4ec573-7d40-4c94-9d25-dae8dfec50c7.png)

When I click on GhostText, and go to emacs interface. the text in emacs buffer comes back like this:
<div>(1) This is a contenteditable div</div><div>(2) abc</div><div>(3) 123</div>

![image](https://user-images.githubusercontent.com/19954880/165986283-c3ca3dbd-fd4a-47dc-a401-a3db1b661998.png)

The text don't came back in with the real line-breaks. How can I solve this problem?

**Comment by fregante** [comment]
GhostText doesn't do content conversion. The content of that contentEditable are `div`s so the editor receives divs.
