### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [fregante/GhostText#225]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@nerrorsec) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by fregante** [comment]
Thank you! My email address is public on my GitHub profile

**Comment by JamieSlome** [comment]
@fregante - thanks for the follow-up 👍 

I will get both reports sent over to the e-mail address stated on your GitHub profile ❤️ 

Just for reference, both can be found here:
[Report 1](https://huntr.dev/bounties/78e0eda4-2745-4a6d-9467-c279289e831c/)
[Report 2](https://huntr.dev/bounties/32a2f0c4-9f59-4485-895c-d5b0069ad43c/)

You can view them directly if you sign-up, but the e-mails I send will allow you to view the contents without any sign-up at all.
