### ISSUE TITLE
GhostText doesn't work in Firefox after latest add-on update (version 22.7.19)

### ISSUE THREAD

**Issue by Serge2702** [fregante/GhostText#227]
# Setup

Browser: Firefox 102.0.1 (64-bit)
Editor: Neovim 0.7

# Description
GhostText doesn't work anymore with Firefox. Yesterday (2022-07-18) I didn't have any issues, but today when I click on the icon nothing happens. There are no error messages in the browser.

I installed the extension in Microsoft Edge and it works fine without any issues. I see that in Firefox's Add-ons page it says the plugin was updated earlier today (2022-07-19), so I guess that is the cause of the problem.

**Comment by fregante** [comment]
It should be fixed in `22.7.19.2014`
