### ISSUE TITLE
GhostText Version 22.7.19.2014 not working in FF

### ISSUE THREAD

**Issue by Reprazent** [fregante/GhostText#228]
# Setup

Browser: Firefox 102.0.1 (64-bit)
Editor: Emacs

# Description

GhostText Version 22.7.19.2014 appears to not detect textareas. It also doesn't start on https://ghosttext.fregante.com/troubleshooting/.

Reverting back to Version 21.3.8 seemed to have fixed the problem for me

**Comment by fregante** [comment]
Can you reinstall the latest version? Firefox probably was showing you the wrong version. 22.7.19 wasn't working but 22.7.19.2014 should

**Comment by Reprazent** [comment]
@fregante Just installed `2.7.19.2014`:

![image](https://user-images.githubusercontent.com/397196/179961840-22b2a7ca-f21c-4bb9-934c-3b558a108021.png)

But that doesn't seem to work for me.

**Comment by Reprazent** [comment]
Thank you! Looking forward to the new release!

**Comment by fregante** [comment]
It seems that Firefox already has it, let me know if it works

**Comment by Reprazent** [comment]
Works like a charm! :rocket:

**Comment by rthewitt** [comment]
Sorry to resurrect, I didn't want to spam new issues.

I'm unable to get 22.7.19.2014 to work at all on Firefox 103.0.1.  I installed both from Firefox Add-ons and directly from the source release.  I also tried the later tag 22.7.20, and previous release 21.3.8.  None are responsive.

However v21.1.28 works perfectly for both Sublime Text and Emacs.

Visiting the web-socket end-point (localhost:4001) directly via the address bar checks out and shifts focus to my editor as expected.

**Comment by fregante** [comment]
Mozilla is f'in unreal. They disabled the newest version 6 days ago without sending any notifications. I'm gonna have to upload a new one. What a PITA

**Comment by fregante** [comment]
22.7.22 is out. Same as 22.7.20

**Comment by rthewitt** [comment]
Hey, you rock!  It works perfectly.  Thanks!
