### ISSUE TITLE
Not work in online coding page

### ISSUE THREAD

**Issue by huangyingw** [fregante/GhostText#231]
I am using GhostText Extension in Chrome, and vim-ghost plugin for nvim.
I find it not work on some of those online coding web page.

For this url:
    https://app.codesignal.com/arcade/intro/level-1/jwr339Kq6e3LQTsfa
all the text is passed to vim.
But write in vim could not sync to the web page input area

For this url:
    https://coderpad.io/NKH2H2H3
only a very small part of the text is passed to vim

**Comment by fregante** [comment]
Thanks for the report. The website uses Monaco editor. The feature requested is tracked in:

- #140
