### ISSUE TITLE
[request] sync with a file at user-specified path

### ISSUE THREAD

**Issue by dan-oak** [fregante/GhostText#232]
i'd like to sync an input field from a web page to a specific file located anywhere i want
i use many websites on competitive programming and it's often when i leave a solution for days or weeks unfinished
this is why it would be great if i had an option to sync with a specific file saved in my user directory instead of creating a tmp file

**Comment by fregante** [comment]
Unfortunately there's no maintainer for the editor side of GhostText, so there's no chance of this being implemented.

If you skip the editor side, it's possible that such a browser extension already exists, but it's not GhostText.
