### ISSUE TITLE
Sublime: Edit text box from existing file instead of creating new tab

### ISSUE THREAD

**Issue by ajfriend** [fregante/GhostText#234]
# Setup

Browser: Chrome
Editor: Sublime

# Description

Thanks for building this. I just discovered it, and it is incredibly useful!

One thing that would help would be the ability to fill in a text box on a web page starting from an existing file I have saved and open in sublime. Would that be possible, or is it already possible?

The use case is that I use this to edit SQL queries that get executed via the web page. I'm often working on them over multiple days, so it would be nice to kick off from where I left off with the saved file.

**Comment by fregante** [comment]
Happy that GhostText is helping you!

Unfortunately I can't think of how to fit this into GhostText’s logic. To the editor, every new connection is just a random new field on a site. Associating "every field on example.com" to a specific file doesn't seem very useful in general and it would require options, etc.

GhostText is pretty much "finished" as a project and I only intend to improve UX and keep compatibility with new editors. New features will be rare
