### ISSUE TITLE
Add support to Open VSX

### ISSUE THREAD

**Issue by Arsemy** [fregante/GhostText#235]
The marketplace that the [VSCodium](https://github.com/VSCodium/vscodium) uses is the [Open VSX](https://open-vsx.org/) instead of the [VSCode marketplace](https://marketplace.visualstudio.com/), so adding to [Open VSX](https://open-vsx.org/)  enables me to use on [VSCodium](https://github.com/VSCodium/vscodium).

You can see more about [here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) and [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

**Comment by fregante** [comment]
GhostText for VSCode is a third party extension, it's not managed by me

**Comment by filiptronicek** [comment]
Hi @fregante, would it be possible to publish the extension now, since it is published by you? It would be greatly appreciated by users of 3rd-party forks of VS Code 🙏.

Me and the team have made [docs](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md), which may be useful for publishing.

**Comment by fregante** [comment]
I can, but if their store causes issues when VSCode's doesn't, I'll disable it. Publishing to more stores just adds one more thing that can go wrong.

**Comment by filiptronicek** [comment]
If something goes wrong, please feel free to ping me; things like this shouldn't happen, since Open VSX should be serving the exact same extension package as the MS store.

**Comment by fregante** [comment]
It's been published, I'll set up CI shortly:

- https://open-vsx.org/extension/fregante/ghost-text

Does VSC’s marketplace allow mentions of open-vsix in the readme?
