### ISSUE TITLE
TiddlyWiki and GhostText not working together

### ISSUE THREAD

**Issue by holdenrohrer** [fregante/GhostText#236]
Setup:
Firefox 104.0.1
Vim 9.0
https://github.com/raghur/vim-ghost
Arch Linux 2022-10-22

Hey! I think there was a regression from #137 at some point because GhostText and TiddlyWiki are still not working together for me (I use vim primarily, but it still shows up with Sublime Text).

Description:
The GhostText addon tells me to click on the field I want to edit (even if there's only one on the page) and then shows a green highlight until I come back about a minute later and click something, so it goes away.

Issue:
GhostText fails to connect on a TiddlyWiki page

Steps to repeat:
This can be repeated here: https://tiddlywiki.com/. Click on the edit symbol (pencil) on one of the notes, and try to edit it through "right-click > edit with GhostText" or by clicking the addon.

I may try writing a patch for this myself since I have a little experience with writing addons, but I figured I should reopen the issue.

_Originally posted by @holdenrohrer in https://github.com/fregante/GhostText/issues/137#issuecomment-1326302411_

**Comment by fregante** [comment]
Sorry for the late answer. It seems that it does work:


https://user-images.githubusercontent.com/1402241/225029232-ac91e30c-1f16-4094-b77b-1751e2abbe15.mov

But it also occasionally fails, the script doesn't seem to be injected in the iframe. I wonder what's causing it. They have a local iframe just for the editor

**Comment by fregante** [comment]
So I found the answer, it's a Firefox bug: they just don't support iframes with the current permissions https://bugzilla.mozilla.org/show_bug.cgi?id=1653408
