### ISSUE TITLE
Add support for CodeMirror 6 (Overleaf)

### ISSUE THREAD

**Issue by niveK77pur** [fregante/GhostText#238]
# Setup

Browser: 

- Chromium (Version 108.0.5359.124 (Official Build) snap (64-bit))
- Firefox (Mozilla Firefox 108.0.2)

Editor: 

- Neovim v0.8.2 using [nvim-ghost](https://github.com/subnut/nvim-ghost.nvim)
- Sublime text (Stable Channel, Build 4143)

# Description

When I focus the text area on Overleaf, I do not see the text appear in neovim/sublime. I only see one big line of HTML which I cannot possibly interact with; see screenshots below from both editors. The behavior is the same for both browsers.

I know for a fact that this worked at some point in the past, because I had used GhostText on Overleaf successfully (with vim (instead of neovim), and with a different plugin). Seeing the issue still persists on Sublime, I hope this warrants an issue. I also hope I am not overlooking something silly!

Also worth pointing out, the first few lines from the text area do appear in the line of HTML. It is a bit more visible in the sublime screenshot. The document happens to start with a bunch of comments `%% .......` which can definitely be spotted here.

## Sublime screenshot
![sublime](https://user-images.githubusercontent.com/10981161/210849134-d2634cc4-6ba2-401b-8b99-d48c9dafa908.png)

## Neovim screenshot

![neovim](https://user-images.githubusercontent.com/10981161/210788612-d13ed05e-6fcf-469d-a583-ca0b51310644.png)

**Comment by fregante** [comment]
My guess is that they updated to CodeMirror 6 and that's not supported yet

**Comment by niveK77pur** [comment]
I have indeed found an article from Nov 29 2022 indicating that they migrated to CodeMirror 6!
https://www.overleaf.com/blog/towards-the-future-a-new-source-editor

In this article, I also noticed that they provide 3 ways of viewing the text/code: `Source`, `Source (legacy)` and `Rich Text`. GhostText still seems to work perfectly fine when I select the 2nd option `Source (legacy)`!

Thank you very much for the heads up! I think this legacy option will do for now as long as Overleaf keeps it around~

Feel free to close this issue if there already exist CodeMirror 6 related issues; the problem here does not seem to be Overleaf specific after all.

**Comment by cpeikert** [comment]
Is there any update on this issue? Overleaf has removed the "legacy" source editor, so there does not seem to be any way to use overleaf with GhostText (which is a big pain point).

**Comment by MahdiNazemi** [comment]
@fregante, Thanks for developing this extremely useful piece of software.

For those who need to access the Legacy editor, but no longer see it as an option, try appending `?legacy_source_editor=true` to the URL.
@cpeikert

**Comment by cpeikert** [comment]
Thanks to both of you for the assistance! The workaround works great (for a while longer, anyway...)

**Comment by fregante** [comment]
Support for CodeMirror 6 has been added in v23.3.16. Let me know how it goes

**Comment by fregante** [comment]
I believe that actually happens to all or most other fields because I don't see the cursor position being updated after the text replacement in the code. 

Can you open an issue?

**Comment by cpeikert** [comment]
Thanks -- I opened new issue #271.
