### ISSUE TITLE
Change file extension?

### ISSUE THREAD

**Issue by robertmarkbram** [fregante/GhostText#242]
# Setup

Browser: Chrome
Editor: VS-Code

# Description

This opens up a `.tmp` file: any way to change the file extension? E.g. `md` for markdown so that I can get markdown features in VS Code?

**Comment by robertmarkbram** [comment]
At least for VS Code, I can easily change the "language mode" for a file and treat the temporary file as markdown. So I can do this already.

**Comment by fregante** [comment]
The VS Code extension is third party. You'll have to open an issue in its repo
