### ISSUE TITLE
The "Disconnected. Report issues" box swings back up too fast for us to click it.

### ISSUE THREAD

**Issue by jidanni** [fregante/GhostText#248]
The "Disconnected. Report issues" box swings back up too fast for us to click it.
We have just finished reading it and now are thinking, and reaching for our mouse, but... too late.

**Comment by fregante** [comment]
![ko](https://user-images.githubusercontent.com/1402241/224266640-cf3df336-9940-435c-bf57-b7c0cacce101.gif)

It stays on for almost 4 seconds, I reckon it's enough time to read 3 words

**Comment by jidanni** [comment]
Okay but if it's the first time a user sees it they need to think for a little while about what it means, and then  they need to think about the safety implications of clicking it, and then when they're all prepared to click it then maybe 30 seconds have even gone by.

But yes, the second and subsequent times they only need one second.

**Comment by fregante** [comment]
Agreed, I opened a more generic issue for notification improvements:

- https://github.com/fregante/GhostText/issues/260
