### ISSUE TITLE
commons.wikimedia.org preferences caveat

### ISSUE THREAD

**Issue by jidanni** [fregante/GhostText#249]
Sure, with the simple test pages, the textbox looks the same in the browser as in the editor.
But for, e.g., https://commons.wikimedia.org/ textboxes or even a highlighted portion thereof, we end up editing an nightmare blob full of HTML brackets.

One moment please... It works fine when logged out of the website... let me disable something in my wiki preferences...

Ah ha! On https://commons.wikimedia.org/ one must disable this preference first, if one has it enabled:

- Enable the new wikitext mode inside the visual editor. It has many of the tools present in the visual editor, uses a similar design, and allows better switching between the two.

So you might want to mention that in the docs.

**Comment by fregante** [comment]
Such explanation doesn't belong to GhostText, but some might find your issue here.

**Comment by fregante** [comment]
I opened an issue tracking a possible UX improvement:

- https://github.com/fregante/GhostText/issues/261
