### ISSUE TITLE
Safari: The browser icon shows nonsense when GhostText is enabled (UTF8 issue)

### ISSUE THREAD

**Issue by fregante** [fregante/GhostText#250]
It's handled here, but still not fixed:

https://github.com/fregante/GhostText/blob/b9f3c690b8849781226ac6e8d9ea5b2b48cc25b2/source/background.js#L101

# Setup

Browser: Safari

# Description

<img width="98" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/224267186-92d53f02-31a9-4007-b558-434de0c63925.png">

# Solutions?

- Add BOM https://stackoverflow.com/a/35807131/288906

**Comment by xeenon** [comment]
Hmm. So `charset` and a BOM didn't work?

**Comment by fregante** [comment]
I haven't tried BOM yet because I'll have to figure out a way to add it after the build. 

As for charset, how? That string lives in the background script. I suppose I could turn it into background.html but I'll have to use a background worker eventually so it would be a temporary fix.

**Comment by xeenon** [comment]
The Xcode encoding only change how the text is parsed for display in Xcode.
