### ISSUE TITLE
Blue frame could have words saying what is going on in it

### ISSUE THREAD

**Issue by jidanni** [fregante/GhostText#251]
Maybe instead or in addition to the blue frame,
![20230311T134215](https://user-images.githubusercontent.com/1230959/224467324-305c9385-32cf-47f5-8acc-e0fd11a7b10a.jpg)
perhaps have some big words diagonally across the screen:
"DRAFT CURRENTLY UNDER EDIT IN ANOTHER WINDOW <details...>"

**Comment by fregante** [comment]
The notifications already do that.

**Comment by jidanni** [comment]
(Well I didn't see any notifications. Also if I did they would only be momentary and not permanent words inside the box which we are not supposed to write into anyway.)

**Comment by fregante** [comment]
Thanks for making GhostText better! Would this help?

- https://github.com/fregante/GhostText/issues/178#issuecomment-1468067629
