### ISSUE TITLE
Make browser buffer read-only during the edit

### ISSUE THREAD

**Issue by jidanni** [fregante/GhostText#252]
When we do an edit, the borders of the textbox become sky blue.

But we can still type inside the box!

That can only lead to mistakes, as we are also editing the buffer elsewhere!

Therefore not only should it become blue, but also become read-only.

**Comment by fregante** [comment]
That is a core functionality of GhostText. Since the field is marked as connected, you can see what you're doing and avoid typing  in it

**Comment by jidanni** [comment]
Actually I wouldn't need the expense of having simultaneous typing, because I only have one big window on my screen at a time. And I only look back at the browser when I'm finished anyway.
But I'm just worried if I get distracted and then come back to the computer and then start typing into the big blue box by accident. Anything I type in there would be lost.

**Comment by fregante** [comment]
> Anything I type in there would be lost.

It wouldn't be lost, that's the point of two-way synchronization

**Comment by jidanni** [comment]
I see.

By the way I found
```
(defcustom atomic-chrome-enable-auto-update t
  "If non-nil, edit on Emacs is reflected to the browser instantly, \
otherwise you need to type \"C-cC-s\" manually."
  :type 'boolean
  :group 'atomic-chrome)

(defcustom atomic-chrome-enable-bidirectional-edit t
  "If non-nil, you can edit both on Chrome text area and Emacs, \
otherwise edit on Chrome is ignored while editing on Emacs."
  :type 'boolean
  :group 'atomic-chrome)
```
if one day I want to tinker with this.
