### ISSUE TITLE
Put cursor at top of file, not bottom

### ISSUE THREAD

**Issue by jidanni** [fregante/GhostText#258]
One notices in the editor (emacs) the cursor is always placed at the bottom of the file.
This is in contrast with where we expect it: the top of the file.

**Comment by fregante** [comment]
What editor are you using?

Cursor position and text selection should be brought over from the field, so if the cursor is at the top in the browser, it should be at the top in the editor too (on connection). Does that happen?

The only issue I know is that the selection isn't updated after the first connection:

- #257

**Comment by jidanni** [comment]
Chrome, emacs.

1. We first click an [edit link](https://commons.wikimedia.org/w/index.php?title=File:20060305Dongshi_Taiwan_Police_Household_visit.jpg&action=edit).
1. Now we click your icon on the browser margin.
1. Voila a buffer appears in emacs.

Well all through this process no cursor position has yet to be
established in the browser.

In the emacs buffer the cursor is at the end of the buffer. We want it
to be in the beginning of the buffer.

We try point-min in an emacs hook:
```
(if(/= 0 (user-uid))
    (progn
      (and (require 'atomic-chrome nil t)
	   (add-hook 'atomic-chrome-edit-mode-hook
		     (lambda ()
		       (setq-local fill-column 99999)
		       (goto-char (point-min))))
	   (atomic-chrome-start-server))))
```
Alas that didn't help.

OK, starting over, and first clicking somewhere in the browser's textbox
before clicking your icon... result: same problem.

Alas, the https://github.com/alpha22jp/atomic-chrome maintainer is not
too active.

**Comment by jidanni** [comment]
Also checking interaction, the cursor also gets put at the bottom both
ways on various interactions.

There is a reference to point-max here...

```
(defun atomic-chrome-send-buffer-text ()
  "Send request to update text with current buffer content."
  (interactive)
  (let ((socket (atomic-chrome-get-websocket (current-buffer)))
        (text (buffer-substring-no-properties (point-min) (point-max))))
    (when (and socket text)
      (websocket-send-text
       socket
       (json-encode
        (if (eq (websocket-server-conn socket) atomic-chrome-server-ghost-text)
            (list (cons "text" text))
          (list '("type" . "updateText")
                (cons "payload" (list (cons "text" text))))))))))
```
