### ISSUE TITLE
Sublime Text doesn't set the initial cursor position

### ISSUE THREAD

**Issue by fregante** [fregante/GhostText#259]
# Setup

Browser: Safari
Editor: Sublime Text

# Broken in Sublime Text

https://user-images.githubusercontent.com/1402241/224997186-292860e2-d530-44ec-a6d2-5480f10a3ef7.mov

# Working in VS Code

https://user-images.githubusercontent.com/1402241/224997202-d7b88c90-6713-4b10-a2c6-121168e81a3f.mov

# Related

- #258

**Comment by ronnix** [comment]
Hi Federico, I ran into this issue, so I looked into it and tried to submit a fix: https://github.com/GhostText/GhostText-for-SublimeText/pull/9
