### ISSUE TITLE
Activation shortcut broken on Firefox on 23.3.16

### ISSUE THREAD

**Issue by shouya** [fregante/GhostText#276]
# Setup

Browser: Firefox 110.0.1 on Linux
Editor: Emacs

# Description

After the extension upgraded to 23.3.16, the shortcut I set to activate GhostText no longer works. However, when clicking on the extension's button from the toolbar the everything still works fine as usual. I suspect it's related to https://github.com/fregante/GhostText/pull/269.

![image](https://user-images.githubusercontent.com/526598/227282038-2d9507f2-b19a-4509-8ce6-55b03ea70c5e.png)

**Comment by fregante** [comment]
Thank you for the report. I had only tested it in Chrome. I think it's due to the new line 137. 

Exploration/PR welcome

**Comment by fregante** [comment]
It should be fixed in 23.3.24
