### ISSUE TITLE
CodeMirror 2 Support (Jenkins)

### ISSUE THREAD

**Issue by rmartine-ias** [fregante/GhostText#282]
Our Jenkins, [way under the hood](https://github.com/stapler/stapler-adjunct-codemirror/blob/master/src/main/resources/org/kohsuke/stapler/codemirror/lib/codemirror.js), uses CodeMirror v.2.38. This was the thing I wanted to use GhostText for (and I'm [not the only one](https://github.com/raghur/vim-ghost/issues/36)).

I slapped together a [CodeMirror page](https://github.com/rmartine-ias/stapler-adjunct-codemirror/tree/demo) from that repo and [some](https://github.com/jenkinsci/jenkins/blob/3948a95cad39437ace90c6092c77482a0306f7ed/war/src/main/webapp/scripts/hudson-behavior.js#L1274) [Jenkins](https://github.com/jenkinsci/jenkins/blob/3948a95cad39437ace90c6092c77482a0306f7ed/core/src/main/resources/lib/hudson/scriptConsole.jelly#L47) [source](https://github.com/jenkinsci/jenkins/blob/3948a95cad39437ace90c6092c77482a0306f7ed/war/src/main/webapp/scripts/prototype.js). Open `index.html` in a browser and hit the GhostText button; it should fail to detect the CodeMirror editor.

Completely understand if supporting older things is out of scope.

<details>
<summary> Full Rendered CodeMirror Block from real Jenkins Script Console </summary>

```html
<form action="script" method="post">
   <textarea id="script" name="script" class="script" style="display: none;"></textarea>
   <div class="CodeMirror" style="border:1px solid black; margin-top: 1em; margin-bottom: 1em">
      <div style="overflow: hidden; position: relative; width: 3px; height: 0px; top: 34.6px; left: 85.6px;"><textarea style="position: absolute; padding: 0px; width: 1px; height: 1em;" autocorrect="off" autocapitalize="none" wrap="off"></textarea></div>
      <div class="CodeMirror-scrollbar" style="z-index: -2; visibility: hidden; display: none;">
         <div class="CodeMirror-scrollbar-inner"></div>
      </div>
      <div class="CodeMirror-scroll cm-s-default" tabindex="-1" draggable="true">
         <div style="position: relative;">
            <div style="position: relative; top: 0px;">
               <div class="CodeMirror-gutter" style="height: 300px;">
                  <div class="CodeMirror-gutter-text">
                     <pre>1</pre>
                     <pre>2</pre>
                     <pre>3</pre>
                  </div>
               </div>
               <div class="CodeMirror-lines">
                  <div style="position: relative; z-index: 0; outline: none; min-width: 136px; margin-left: 28px;">
                     <div style="position: absolute; width: 100%; height: 0px; overflow: hidden; visibility: hidden;">
                        <pre><span class="cm-variable">yeah</span><span class="cm-operator">!!</span><span>​</span></pre>
                     </div>
                     <pre class="CodeMirror-cursor" style="top: 28px; left: 51px;">&nbsp;</pre>
                     <pre class="CodeMirror-cursor" style="visibility: hidden; left: 135px;">&nbsp;</pre>
                     <div style="position: relative; z-index: -1; display: none;"></div>
                     <div style="">
                        <pre><span class="cm-atom">this</span> <span class="cm-variable">is</span></pre>
                        <pre><span class="cm-variable">some</span> <span class="cm-variable">groovy</span> <span class="cm-variable">code</span></pre>
                        <pre><span class="cm-variable">yeah</span><span class="cm-operator">!!</span></pre>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div align="right"><span class="yui-button yui-submit-button submit-button primary" id="yui-gen9" name="Submit"><span class="first-child"><button type="button" tabindex="0" id="yui-gen9-button">Run</button></span></span></div>
   <div><input type="hidden" name="Jenkins-Crumb" value="ThisLooksLikeDataIShouldOmit--Riley"></div>
   <div><input type="hidden" name="json" value="init"></div>
</form>
```

</details>

**Comment by fregante** [comment]
Sorry for the delay. I would accept a minimal PR to add support for CodeMirror 2 — or I'm open for sponsorship, but otherwise I can't spend time on this.

Depending on its API, this could be straightforward. Refer to CodeMirror 5’s implementation (CM6 got crazy, don't look at that)

https://github.com/fregante/GhostText/blob/388255d54f544112ad6dea214c2d94fb02678962/source/advanced-editors-messenger.js#L80-L96

Closing for now, PR still welcome

**Comment by rmartine-ias** [comment]
Thank you for the update, and completely understand!
