### ISSUE TITLE
Ghost Text Not Working

### ISSUE THREAD

**Issue by ST-SKumar** [fregante/GhostText#290]
# Setup

Browser: Google Chrome
Editor: Sublime Text 4

# Description
open not working it showing connected and opens automatically Sublime without text textarea in sublime text

**Comment by fregante** [comment]
It works. I'd need more information than "not working"

**Comment by ST-SKumar** [comment]
When i run GhostText in Chrome then Sublime Editor Open's but not open's the textarea, opened only Blank Sublime Editor or open's disconnected page Contents.

**Comment by fregante** [comment]
https://ghosttext.fregante.com/troubleshooting/

**Comment by ST-SKumar** [comment]
I Tried, not helpful this Troubleshooting.
