### ISSUE TITLE
Problem with two-way sync on firefox and neovim

### ISSUE THREAD

**Issue by ronakmsoni** [fregante/GhostText#294]
Basically the same as #154 but three years later: problems with two-way sync in overleaf.com.
The editor is able to receive the text with no problems, but my edits don't show up in overleaf.

I tried the following combinations:

| Browser | Text editor | Two-Way sync Works? |
| --------|----------|---------|
| Firefox | SublimeText | Yes, unless I have used the [actualvim](https://github.com/lunixbochs/actualvim) plugin since starting the editor |
| Firefox | NeoVim | No |
| Safari | NeoVim | Yes |

Happy to try other combinations if developers want me to.

The recreate: open overleaf, start ghostext, type stuff and see if it appears in overleaf.
I'm on an M1 mac, running MacOS12.

**Comment by fregante** [comment]
I'm confused by your support table, not sure why it would work in Safari but not Firefox.

Have you seen this? Particularly the video demo: https://github.com/fregante/GhostText/pull/285

Can you try Chrome?

**Comment by ronakmsoni** [comment]
Sorry for wasting your time, but it's working now. I had already granted iframes access, but I must have messed something up cos i was trying a bunch of different stuff in quick succession.
