### ISSUE TITLE
submit form changes from text editor 

### ISSUE THREAD

**Issue by realskk** [fregante/GhostText#298]
### Description and repro

Hello,

Since issue #44 and #48 were opened, almost 10 years have passed, but is the result not changed?

I often use slack. Thanks to GhostText, I'm happy I can type messages in emacs.  But in case I can submit a message from text editor, I don't need to switch window and push 'send now' button for each message.

Best Regards,
Hiroshi

ps. I couldn't change label except 'bug'... Probably this might be 'enhancement' or so. 

### Browser(s) tried

google chrome 116

### Editor(s) tried

emacs

**Comment by fregante** [comment]
I think the major issue here is that each editor extension has to define a way to send the "Submit" event. This can't just override other shortcuts but should probably be its own command that appears in the dropdown.

The second issue is that not every website supports the same "submit" shortcut: some submit on Enter, some cmd-enter. So how does one configure which operation to send?

Closing for now but if you can think of an elegant solution to handle both, I'd be happy to accept a PR that adds support for a "Submit" event. The editors can follow later.

**Comment by aemonge** [comment]
I'm interested on this too, just here to :+1:  vote for the feature
