### ISSUE TITLE
textarea modified by javascript

### ISSUE THREAD

**Issue by windybb** [fregante/GhostText#299]
### Description and repro

GT does not notice text changes edited by java script, e.g. by a WYSIWYG editor. 
Inserting a tag edits the text in the textarea, but does not change the data in the text editor.

When the text editor is focused, the changes on textarea is cleared, of course.

I assume it is because keystroke events and text change events do not arise, is there any way to fix this? 
We would be very happy if it could be implemented in a way by polling.

### Browser(s) tried

chrome

### Editor(s) tried

emacs

**Comment by fregante** [comment]
This is tracked in:

- https://github.com/fregante/GhostText/issues/84
