### ISSUE TITLE
Not Working for Cinny and Element

### ISSUE THREAD

**Issue by eeriemyxi** [fregante/GhostText#303]
### Description and repro

When I activate the extension on the input fields of Cinny and Element (Matrix clients), it does succeed to at least connect, but after that if I try to use my text editor to change the text content, I cannot no longer send the text from the client nor can I delete what was entered using my text editor. There is a lot more to tell but it's so inconsistent that I cannot cover it in textual form.

It would be better if you review these clients and see for yourself how the extension behaves there. The client links are:
* http://app.element.io/
* http://app.cinny.in/

### Browser(s) tried

Vivaldi 6.4.3160.38 (Official Build) snapshot (64-bit) 

### Editor(s) tried

Neovim

**Comment by fregante** [comment]
GhostText isn't particularly suitable for chatting because it does not support sending messages via shortcut. See https://github.com/fregante/GhostText/issues/298
