### ISSUE TITLE
Doesn't seem to work on StackOverflow.com

### ISSUE THREAD

**Issue by wernerdegroot** [fregante/GhostText#305]
### Description and repro

1. Go to any StackOverflow.com thread. For example: https://stackoverflow.com/questions/51169947/soap-port-uses-a-non-standard-soap-1-2-binding
2. Focus on `<textarea>` for answer: 
![image](https://github.com/fregante/GhostText/assets/7254709/257107cd-047a-4651-9eb9-2975f5b60fa0)
3. Activate GhostText
4. Observe that plugin doesn't work (I use VSCode)

### Browser(s) tried

Chrome

### Editor(s) tried

VSCode

**Comment by fregante** [comment]
See https://ghosttext.fregante.com/troubleshooting/

![all](https://github.com/fregante/GhostText/assets/1402241/fef81d7a-16bc-4bcd-bf7e-66f314b92d96)

**Comment by fregante** [comment]
This might be at play:

- https://github.com/fregante/GhostText/issues/274

Unfortunately the editor can be open in any workspace you have open, so that means you have to go find where it was opened.

For this reason I prefer Sublime Text, because the plugins run across multiple windows.

**Comment by wernerdegroot** [comment]
I was aware of the workspace-issue, but for some reason it does not work for me (even with a completely clean VSCode window). I will try Sublime for now.

**Comment by wernerdegroot** [comment]
StackOverflow.com (with Chrome) and Sublime also doesn't seem to work for me (while the test page _does_ work)

**Comment by wernerdegroot** [comment]
I get the following error when opening the page:

![image](https://github.com/fregante/GhostText/assets/7254709/f880c4fe-0ed1-446f-bba7-6f31364e7df4)

**Comment by fregante** [comment]
I'll reopen to track it, but I'm not sure what's failing. Maybe it's broken in your chrome version. What are you using?

**Comment by wernerdegroot** [comment]
> I'll reopen to track it, but I'm not sure what's failing. Maybe it's broken in your chrome version. What are you using?

Version 120.0.6099.129 (Official Build) (arm64)

**Comment by fregante** [comment]
It works for me in Chrome too:

<img width="903" alt="Screenshot 1" src="https://github.com/fregante/GhostText/assets/1402241/8544b6b6-fb63-431c-81db-de0950c3fe82">


I'm not sure what part is failing. Can you check the errors in the background page? https://stackoverflow.com/a/10258029/288906

**Comment by wernerdegroot** [comment]
Nothing there:

<img width="1512" alt="image" src="https://github.com/fregante/GhostText/assets/7254709/d9fc45de-53c8-4781-b672-60bb93058218">

When I start a new incognito window, it _does_ work with Chrome. So strange...

**Comment by wernerdegroot** [comment]
I manually deleted all my cookies and now it works.........

**Comment by fregante** [comment]
Yessss

I wonder if some other extension also caused trouble, rather than just the cookies. Kinda strange
