### ISSUE TITLE
The connection to the port is broken. Browser Firefox developer

### ISSUE THREAD

**Issue by Gaze-Rumit** [fregante/GhostText#321]
### Description and repro

Sorry for my English. 
The problem started about a week ago. When using "Ghost Text", the connection breaks.
There are errors in the console:

### Browser(s) tried

Firefox developer

### Editor(s) tried

Sublime text

**Comment by fregante** [comment]
Are you using the latest version? https://github.com/fregante/GhostText/issues/318 should have fixed this issue

**Comment by fregante** [comment]
Tracked in https://github.com/fregante/GhostText/issues/317
