### ISSUE TITLE
Html tag includes in the text area

### ISSUE THREAD

**Issue by bushnerd** [fregante/GhostText#329]
### Description and repro

chatgpt.com textarea.

There are lots of html tags include in neovim.
![image](https://github.com/user-attachments/assets/a774dd52-e808-48a1-b466-d803f4e93ae9)

### Browser(s) tried

chrome

### Editor(s) tried

neovim

**Comment by fregante** [comment]
Yes that’s by design. The field is not a raw textarea but it contains HTML
