### ISSUE TITLE
Running GhostText on `chrome-extension://` pages like TamperMonkey’s

### ISSUE THREAD

**Issue by drhouse** [fregante/GhostText#55]
I write a lot of userscripts for Tampermonkey and just discovered GhostText. I thought it would be neat if I could click the 'new script' button in there, then use GhostText to switch and start writing in Sublime right away. I imagine it would involve changing some permissions in the manifest file. Currently, there's a kind of Tampermonkey workaround where you can include a local file as a '@require', but this other way would be more convenient.

**Comment by bfred-it** [comment]
Unfortunately that's not possible. The `activeTab` permission does not include `chrome-extension://` urls and they cannot be manually added to the manifest file :(

<img width="467" alt="malformed pattern error" src="https://cloud.githubusercontent.com/assets/1402241/11062480/132afd24-8764-11e5-9986-a06aa19c5a55.png">

**Comment by bfred-it** [comment]
We'll have to wait for this: https://code.google.com/p/chromium/issues/detail?id=153245

**Comment by Enteleform** [comment]
@bfred-it 

I just checked out the chromium issue you linked to, and someone posted this a few months after your comment:

> **Jan 11 2016**
I think it's fixed now a few months/years ago: https://chromium.googlesource.com/chromium/src/+/92e1442120f561f9344bae80b3bd97d2f7d956cb%5E%21/#F0  

&nbsp;  

-----

&nbsp;  
I'm too familiar w/ Chrome Extensions, but was wondering if that changes anything regarding this issue.

**Comment by bfred-it** [comment]
If it works it works, if it doesn't there's no special API to make it work.

**Comment by fregante** [comment]
I tried again and the error is now very specific when running `executeScript` on the tab:

```
Error: Cannot access a chrome-extension:// URL of different extension
```
