### ISSUE TITLE
Finalize syntax-by-extension support

### ISSUE THREAD

**Issue by fregante** [fregante/GhostText#65]
- [x] Wait for https://github.com/Cacodaimon/GhostText-for-SublimeText/issues/62
- [ ] Move `get_syntax_by_host()` to the Browser side, it should just send the extension, **if** any is found, otherwise ST should just use its default
- [ ] Update GT-ST docs
- [ ] Push ST release

Related:
https://github.com/Cacodaimon/GhostText-for-Chrome/issues/3
https://github.com/Cacodaimon/GhostText-for-Chrome/issues/25

**Comment by subnut** [comment]
Ping! for updates...

**Comment by fregante** [comment]
Most of the new features will likely only be added via PR by others. I’d rather focus on stability

**Comment by fregante** [comment]
Unfortunately I don’t think this is ever practical. Any domain can contain any syntax. GitHub is not only markdown. WordPress is not only HTML. Etc. Any work would still be guesswork and just introduce issues.

I added a mention to send the full URL on https://github.com/fregante/GhostText/issues/255, so maybe the editor can implement format may as best as it can. 

Nowadays editors could automatically detect the syntax anyway
